# Generated by Django 3.2 on 2022-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
