# Generated by Django 3.2 on 2022-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='show_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
