# Generated by Django 2.2.2 on 2021-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_menudetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
