# Generated by Django 3.2 on 2022-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_restaurant_show_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
