# Generated by Django 3.2 on 2022-07-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_menu_show_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationuser',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='locationuser',
            name='distance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ordertrans',
            name='location_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.locationuser'),
        ),
    ]
