# Generated by Django 3.2 on 2022-06-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_auto_20220102_1542'),
        ('delivery', '0004_auto_20211204_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detail_1st', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_2nd', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('1', 'INITIAL'), ('2', 'PROCESSING'), ('3', 'DONE'), ('4', 'FAILED')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.customuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='menu_detail_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='ordertrans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='delivery.ordertrans', blank=True, null=True),
            preserve_default=False,
        ),
    ]
