# Generated by Django 3.2 on 2022-07-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20220714_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertrans',
            name='payment_method',
            field=models.CharField(choices=[('1', 'CASH'), ('2', 'TRANSFER')], default='1', max_length=10),
        ),
    ]
