# Generated by Django 3.2 on 2022-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_ordertrans_distance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertrans',
            name='status',
            field=models.CharField(choices=[('1', 'INITIAL'), ('2', 'PROCESSING'), ('3', 'CONFIRM'), ('4', 'DONE'), ('6', 'REJECT'), ('7', 'FAILED')], default='1', max_length=10),
        ),
    ]
