# Generated by Django 2.2.2 on 2021-10-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20211005_2137'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=100)),
                ('num_liter', models.CharField(max_length=5)),
                ('eco', models.BooleanField(default=False)),
                ('bensin', models.BooleanField(default=False)),
                ('diesel', models.BooleanField(default=False)),
                ('rimula', models.BooleanField(default=False)),
                ('eco_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('semi_sync_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sync_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.CarBrand')),
            ],
        ),
    ]
