# Generated by Django 2.2.2 on 2021-12-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.Item')),
                ('image', models.ImageField(upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculateprice',
            name='brand',
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionform',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'INITIAL'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='INITIAL', max_length=10),
        ),
    ]
