# Generated by Django 2.2.2 on 2021-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20211205_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionform',
            name='is_notify',
            field=models.BooleanField(default=False),
        ),
    ]
