# Generated by Django 2.2.2 on 2022-01-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20211227_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='item.Item'),
        ),
    ]
