# Generated by Django 2.2.2 on 2022-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20220109_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
