# Generated by Django 2.2.2 on 2022-02-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20220109_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='liter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
