# Generated by Django 2.2.10 on 2022-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20220201_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionform',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
