# Generated by Django 3.2 on 2022-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211211_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
