# Generated by Django 2.2.10 on 2021-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linelogin',
            name='mode',
            field=models.IntegerField(choices=[('1', 'FORM'), ('2', 'HISTORY'), ('3', 'CALCULATEPRICE')], default=1),
            preserve_default=False,
        ),
    ]
