# Generated by Django 2.2.2 on 2021-09-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_transactionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_id', models.CharField(max_length=20)),
                ('channel_secret', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_id', models.CharField(max_length=20)),
                ('channel_access_token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionform',
            name='line_official',
        ),
        migrations.AddField(
            model_name='transactionform',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LineOfficial',
        ),
        migrations.AddField(
            model_name='transactionform',
            name='line_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='line.LineMessage'),
        ),
    ]
