# Generated by Django 2.2.10 on 2021-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_linelogin_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linelogin',
            name='mode',
            field=models.IntegerField(choices=[(1, 'FORM'), (2, 'HISTORY'), (3, 'CALCULATEPRICE')]),
        ),
    ]
