# Generated by Django 2.2.2 on 2021-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_auto_20211030_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
