# Generated by Django 2.2.2 on 2022-01-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_auto_20211210_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
